config/routes.rb
Rails.application.routes.draw do
  get 'landing', to: 'page#name', as: 'landing'
  get 'name', to: 'page#name', as: 'name'
  get 'brandName', to: 'page#brandName', as: 'brandName'
  get 'deals', to: 'page#deals', as: 'deals'
  root 'page#landing'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/page_controller.rb
class PageController < ApplicationController
    def landing
        render html: 'Welcome to Cigarrete Saving The Day'
    end
    def name
    end
    def brandName
    end
    def deals
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsControllersRoutesViews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/brandName.html.erb
<h1> UNIQUE CIGARRETE BRAND </h1>
<ul>
<li> Twisted Cig </li>
<li> White Claw </li>
<li> Cognac Cig </li>
<li> Edible Cig </li>
<li> Dragon Cig </li>
<li> Bird Cig</li>
<li> Water Cig </li>
<li> Dog Cig </li>
<li> Cat Cig </li>
<li> Monkey Cig</li>
<li> Tiger War </li>
<li> Human Centipede </li>
<li> Call of Duty </li>

</ul>

<ul>
    <li> <%= link_to 'See OUR UNIQUE Deals', deals_path %> </li>
</ul>

app/views/page/deals.html.erb
<h1> DEALS OF THE DAY </h1>
<ul>
<li> Single Packs: BUY ONE GET ONE HALF OFF </li>
<li> BUY TWO CARTONS GET $2 OFF </li>
<li> SINGLE TWISTED CIG $.50 </li>
<li> FIRST TIME CUSTOMER, CHOOSE 1 OF THE BRAND FOR FREE </li>
</ul>
<ul>
    <li><%= link_to 'Go back to our main page', name_path %></li>
</ul>

app/views/page/name.html.erb
<h1> Unique Cigarrete Shop </h1>
<h2> DESCRIPTION</h2>
<h3> HI, WELCOME TO UNIQUE CIGARRETE SHOP WHERE YOU CAN FIND UNIQUE CIGARRETES THAT NO ONE HAS EVER SMOKED BEFORE.</h3>
<br> <br>
<h4> HOURS OF OPEATION: MONDAY: 10 AM - 9 PM  </h4>
<h4>MONDAY: 10 AM - 9 PM</h4>
<h4> TUESDAY: 10 AM - 9 PM  </h4>
<h4> WEDNESDAY: 10 AM - 9 PM  </h4>
<h4> THURSDAY: 10 AM - 9 PM  </h4>
<h4> FRIDAY: 10 AM - 9 PM  </h4>
<h4> SATURDAY: 10 AM - 8 PM  </h4>
<h4> SUNDAY: CLOSED! GOING TO THE CLUB! </h4>
<h4> Contact info: 1(215)-453-4544</h4>
<ul>
    <li> <%= link_to 'See the Brand', brandName_path %> </li>
</ul>